
# HISTCONTROL=ignoredups:ignorespace:erasedups
# HISTIGNORE="pwd:ls:ll:cd:cd .."

PS1='\033[1;37m\W\033[0m$(__git_ps1 "|\033[0;33m%s\033[0m") '

# PATH=$PATH:~/android-sdk/tools
# PATH=$PATH:~/android-sdk/platform-tools

alias ll='ls -alh'
